"""Update Plan model with correct columns

Revision ID: 38050b846173
Revises: 120643bd6ef5
Create Date: 2026-09-10 00:13:49.728505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38050b846173'
down_revision = '120643bd6ef5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_assignments',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('membership_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=60), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['membership_id'], ['company_memberships.id'], ),
    sa.PrimaryKeyConstraint('job_id', 'membership_id')
    )
    op.create_table('job_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.Enum('REQUIRED', 'ORDERED', 'AVAILABLE', 'USED', name='materialstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', name='jobstagestatus'), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'position', name='uq_job_stage_position')
    )
    op.create_table('next_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('assigned_membership_id', sa.Integer(), nullable=False),
    sa.Column('created_by_membership_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='nextactionstatus'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(CASE WHEN lead_id IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN client_id IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN job_id IS NOT NULL THEN 1 ELSE 0 END) = 1', name='ck_next_action_one_target'),
    sa.ForeignKeyConstraint(['assigned_membership_id'], ['company_memberships.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by_membership_id'], ['company_memberships.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('next_actions', schema=None) as batch_op:
        batch_op.create_index('ix_next_action_assignee_status', ['assigned_membership_id', 'status'], unique=False)
        batch_op.create_index('ix_next_action_company_due', ['company_id', 'due_at'], unique=False)

    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('actor_membership_id', sa.Integer(), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(CASE WHEN lead_id IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN client_id IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN job_id IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN conversation_id IS NOT NULL THEN 1 ELSE 0 END) = 1', name='ck_activity_one_target'),
    sa.ForeignKeyConstraint(['actor_membership_id'], ['company_memberships.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index('ix_activity_company_created', ['company_id', 'created_at'], unique=False)

    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_membership_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(CASE WHEN lead_id IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN client_id IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN job_id IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN message_id IS NOT NULL THEN 1 ELSE 0 END) = 1', name='ck_attachment_one_target'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_membership_id'], ['company_memberships.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.create_index('ix_attachment_company_created', ['company_id', 'created_at'], unique=False)

    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_eur', sa.Numeric(precision=10, scale=2), nullable=True))

    op.execute("UPDATE plans SET price_eur = price_gbp")

    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.alter_column('price_eur', nullable=False)
        batch_op.drop_column('price_gbp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_gbp', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))

    op.execute("UPDATE plans SET price_gbp = price_eur")

    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.alter_column('price_gbp', nullable=False)
        batch_op.drop_column('price_eur')

    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_index('ix_attachment_company_created')

    op.drop_table('attachments')
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index('ix_activity_company_created')

    op.drop_table('activities')
    with op.batch_alter_table('next_actions', schema=None) as batch_op:
        batch_op.drop_index('ix_next_action_company_due')
        batch_op.drop_index('ix_next_action_assignee_status')

    op.drop_table('next_actions')
    op.drop_table('job_stages')
    op.drop_table('job_materials')
    op.drop_table('job_assignments')

    op.execute("DROP TYPE IF EXISTS jobstagestatus")
    op.execute("DROP TYPE IF EXISTS materialstatus")
    op.execute("DROP TYPE IF EXISTS nextactionstatus")
    # ### end Alembic commands ###
